"""
Generación de ids para tablas sin autoincremento (id INTEGER PRIMARY KEY,
sin SERIAL/IDENTITY). Es el mismo patrón que ya traía el proyecto para
Lotes/Usuarios/Reservas — lo centralizamos aquí para no repetirlo en cada
controlador, y le agregamos un candado para que dos peticiones simultáneas
no puedan calcular el mismo "siguiente id".

LIMITACIÓN CONOCIDA: esto NO resuelve que Lote.id y Usuario.id sigan
viniendo directamente del cliente en vez de ser calculados por el backend
(esquemas_lotes.LoteCrear.id / esquemas_usuarios.UsuarioCrear.id). Esa es
una decisión de diseño anterior a este módulo; cambiarla implicaría tocar
los formularios de registro y de publicar lote, y no se hizo aquí por
alcance/riesgo. Lo ideal a futuro es migrar esas tablas a
GENERATED BY DEFAULT AS IDENTITY y dejar de mandar el id desde el frontend.
"""

from sqlalchemy import func, text
from sqlalchemy.orm import Session


def siguiente_id(db: Session, modelo) -> int:
    """
    Calcula el próximo id disponible para `modelo` (MAX(id) + 1).

    Usa un advisory lock de PostgreSQL con alcance de transacción
    (`pg_advisory_xact_lock`), tomado sobre el nombre de la tabla, para que
    dos peticiones concurrentes que estén creando filas en la misma tabla
    no puedan leer el mismo MAX(id) y terminar generando un id duplicado.
    El candado se libera solo al hacer commit/rollback de la transacción
    de `db`, así que el caller debe hacer `db.commit()` normalmente
    después de insertar — no hace falta liberar nada a mano.

    También considera los objetos que ya se agregaron a esta MISMA sesión
    con `db.add(...)` pero todavía no se guardaron con flush/commit — sin
    esto, dos llamadas seguidas a esta función para el mismo modelo dentro
    de una sola petición (por ejemplo, crear dos notificaciones en la misma
    función) devolvían el mismo id, porque la fila de la primera todavía no
    existía para la base de datos cuando se calculaba el MAX() de la
    segunda. Esto se detectó probando el flujo de "reserva con plazo de
    pago", que crea dos notificaciones seguidas en la misma petición.
    """
    tabla = modelo.__tablename__
    db.execute(text("SELECT pg_advisory_xact_lock(hashtext(:tabla))"), {"tabla": tabla})

    maximo_bd = db.query(func.max(modelo.id)).scalar() or 0
    maximo_pendiente = max(
        (obj.id for obj in db.new if isinstance(obj, modelo) and obj.id is not None),
        default=0,
    )
    return max(maximo_bd, maximo_pendiente) + 1
